### ISSUE TITLE
Support for 1.21.4

### ISSUE THREAD

**Issue by Grabsky** [HalbFettKaese/WireframeDisplay#1]
Hey, looks like pack is no longer working as of 1.21.4. Could you please look into that?
```
/execute align xyz run summon item_display ~ ~ ~ {item: {id:"coal",components: {"minecraft:item_model":"wireframe:wireframe_white"}}, transformation:{scale:[1f,1f,1f],left_rotation:[0f,0f,0f, 1f],right_rotation:[0f,0f,0f,1f],translation:[0.5,0.5,0.5]}}
```
![image](https://github.com/user-attachments/assets/50fb90bf-2b24-4617-a329-f506190d84c2)

I suspect the problem is that item model definition is missing from the resource-pack.
https://minecraft.wiki/w/Items_model_definition

**Comment by HalbFettKaese** [comment]
Thank you for your Report!

I've added the new item models feature. You can check it out right here:
https://github.com/HalbFettKaese/WireframeDisplay/releases/tag/V1.0.3
